# Generated by Django 4.0.5 on 2022-08-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='NumPeople',
            field=models.IntegerField(default=1, verbose_name='Numero de Personas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='NumRoom',
            field=models.IntegerField(default=1, verbose_name='Numero de Habitaciones'),
            preserve_default=False,
        ),
    ]
