# Generated by Django 4.0.5 on 2022-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_room_numpeople_room_numroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=300, verbose_name='Apellidos')),
                ('password1', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('username', models.CharField(max_length=100, verbose_name='Nombres')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Uuarios',
                'ordering': ['-username'],
            },
        ),
    ]
