# Generated by Django 4.0.5 on 2022-08-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
