# Generated by Django 4.0.5 on 2022-08-10 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Seleccione la fecha de reservacion'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Habitacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
