# Generated by Django 4.0.5 on 2022-08-10 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_alter_reservation_date_alter_reservation_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created'], 'verbose_name': 'Reservacion', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion'),
        ),
    ]
