# Generated by Django 4.0.5 on 2022-08-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_alter_reservation_options_reservation_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date'], 'verbose_name': 'Reservacion', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated',
        ),
    ]
