# Generated by Django 4.0.5 on 2022-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_alter_reservation_options_remove_reservation_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Fecha de Reservacion'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.TextField(max_length=100, verbose_name='Habitacion'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.TextField(max_length=100, verbose_name='Usuario'),
        ),
    ]
