# Generated by Django 4.0.5 on 2022-08-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0012_alter_reservation_date_alter_reservation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.CharField(max_length=100, verbose_name='Habitacion'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Usuario'),
        ),
    ]
