# Generated by Django 4.0.5 on 2022-08-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date'], 'verbose_name': 'Reservacion', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='email',
            new_name='mail',
        ),
    ]
