# Generated by Django 4.0.5 on 2022-08-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0016_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('mail', models.CharField(max_length=200, verbose_name='E-mail')),
                ('cell', models.CharField(max_length=100, verbose_name='Telefono')),
                ('msg', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('room', models.CharField(max_length=150, verbose_name='Habitacion')),
                ('dispo', models.CharField(max_length=100, verbose_name='Disponibilidad')),
                ('contac', models.CharField(max_length=100, verbose_name='Contactarme por')),
                ('date', models.CharField(max_length=100, verbose_name='Fecha para contactar')),
                ('hour', models.CharField(max_length=100, verbose_name='Hora para contactar')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
            ],
            options={
                'verbose_name': 'Asesoria',
                'verbose_name_plural': 'Asesorias',
                'ordering': ['-created'],
            },
        ),
    ]
