# Generated by Django 4.0.5 on 2022-08-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0017_asesoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoria',
            name='contac',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='date',
        ),
        migrations.RemoveField(
            model_name='asesoria',
            name='hour',
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='msg',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
