# Generated by Django 4.0.5 on 2022-08-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0018_remove_asesoria_contac_remove_asesoria_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='Estado',
            field=models.CharField(default=1, max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
