# Generated by Django 4.0.5 on 2022-08-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0019_asesoria_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoria',
            name='Estado',
        ),
    ]
