# Generated by Django 4.0.5 on 2022-08-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0020_remove_asesoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
