# Generated by Django 4.0.5 on 2022-08-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0022_remove_asesoria_dispo_remove_asesoria_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesoria',
            name='state',
        ),
    ]
